# Generated by Django 4.0.4 on 2022-06-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=3)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=3)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolios.portfolio')),
            ],
        ),
    ]
