# Generated by Django 4.0.4 on 2022-06-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0002_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
