# Generated by Django 4.0.4 on 2022-06-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolios', '0003_alter_stock_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='actual',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
