# Generated by Django 4.0.4 on 2022-05-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Company/Fund')),
                ('ticker', models.CharField(max_length=5, verbose_name='Ticker')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('holdings', models.PositiveIntegerField(verbose_name='Holdings')),
                ('equity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Equity')),
                ('goal', models.PositiveIntegerField(verbose_name='Goal Percentage')),
                ('current', models.PositiveIntegerField(verbose_name='Current Percentage')),
            ],
        ),
    ]
